Traceback (most recent call last):
  File "C:\Users\zimme\miniconda3\envs\cvas\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\zimme\miniconda3\envs\cvas\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zimme\miniconda3\envs\cvas\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zimme\miniconda3\envs\cvas\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\zimme\miniconda3\envs\cvas\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\zimme\miniconda3\envs\cvas\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\zimme\miniconda3\envs\cvas\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
wav=wv.read("./Data/zc06_204a22410-24210.wav")
fs=wav.rate
data=wav.data[int(4*fs):int(14*fs),:]
tt=np.arange(data.shape[0])/fs
plt.figure(figsize=(12,5))
plt.plot(tt,data)
plt.xlabel('Time [s]')
plt.show()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [1;32mIn[2], line 1[0m
[1;32m----> 1[0m wav[38;5;241m=[39m[43mwv[49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m./Data/zc06_204a22410-24210.wav[39;49m[38;5;124;43m"[39;49m[43m)[49m
[0;32m      2[0m fs[38;5;241m=[39mwav[38;5;241m.[39mrate
[0;32m      3[0m data[38;5;241m=[39mwav[38;5;241m.[39mdata[[38;5;28mint[39m([38;5;241m4[39m[38;5;241m*[39mfs):[38;5;28mint[39m([38;5;241m14[39m[38;5;241m*[39mfs),:]

File [1;32m~\miniconda3\envs\cvas\Lib\site-packages\wavio.py:206[0m, in [0;36mread[1;34m(file)[0m
[0;32m    156[0m [38;5;28;01mdef[39;00m [38;5;21mread[39m(file):
[0;32m    157[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[0;32m    158[0m [38;5;124;03m    Read a WAV file.[39;00m
[0;32m    159[0m 
[1;32m   (...)[0m
[0;32m    204[0m [38;5;124;03m    with values that have been sign-extended.[39;00m
[0;32m    205[0m [38;5;124;03m    """[39;00m
[1;32m--> 206[0m     wav [38;5;241m=[39m [43m_wave[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mfile[49m[43m)[49m
[0;32m    207[0m     rate [38;5;241m=[39m wav[38;5;241m.[39mgetframerate()
[0;32m    208[0m     nchannels [38;5;241m=[39m wav[38;5;241m.[39mgetnchannels()

File [1;32m~\miniconda3\envs\cvas\Lib\wave.py:631[0m, in [0;36mopen[1;34m(f, mode)[0m
[0;32m    629[0m         mode [38;5;241m=[39m [38;5;124m'[39m[38;5;124mrb[39m[38;5;124m'[39m
[0;32m    630[0m [38;5;28;01mif[39;00m mode [38;5;129;01min[39;00m ([38;5;124m'[39m[38;5;124mr[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mrb[39m[38;5;124m'[39m):
[1;32m--> 631[0m     [38;5;28;01mreturn[39;00m [43mWave_read[49m[43m([49m[43mf[49m[43m)[49m
[0;32m    632[0m [38;5;28;01melif[39;00m mode [38;5;129;01min[39;00m ([38;5;124m'[39m[38;5;124mw[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mwb[39m[38;5;124m'[39m):
[0;32m    633[0m     [38;5;28;01mreturn[39;00m Wave_write(f)

File [1;32m~\miniconda3\envs\cvas\Lib\wave.py:279[0m, in [0;36mWave_read.__init__[1;34m(self, f)[0m
[0;32m    277[0m [38;5;28mself[39m[38;5;241m.[39m_i_opened_the_file [38;5;241m=[39m [38;5;28;01mNone[39;00m
[0;32m    278[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(f, [38;5;28mstr[39m):
[1;32m--> 279[0m     f [38;5;241m=[39m [43mbuiltins[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mf[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m'[39;49m[43m)[49m
[0;32m    280[0m     [38;5;28mself[39m[38;5;241m.[39m_i_opened_the_file [38;5;241m=[39m f
[0;32m    281[0m [38;5;66;03m# else, assume it is an open file object already[39;00m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: './Data/zc06_204a22410-24210.wav'

